version: '3'
services:
  db:
    image: mariadb:5
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
    - '3306:3306'
  xtrabackup:
    image: webtoolsdev/xtrabackup:latest
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./backups:/backups
      - db-data:/var/lib/mysql

volumes:
  db-data:
